name: Update LeetCode problem data

on:
  schedule:
    # New problems are usually available each week after a LeetCode contest!
    # Note that in UTC time the weekly contests are on Sundays.
    # See also: https://crontab.guru/
    - cron: 5 4 * * 0

  # Allows running this workflow manually from the repository's Actions tab.
  workflow_dispatch:

# Allow only one concurrent run, skipping runs queued between the run
# Cancel runs in progress as well, since the latest one likely supersedes previous ones.
concurrency:
  group: update-problem-data
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-problem-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up everything
        uses: ./.github/workflows/set-up-everything

      - name: Get LeetCode problem list
        run: (cd packages/get-leetcode-problem-list && yarn start) && mv -f packages/get-leetcode-problem-list/problems.jsonl archive/

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: leetcode-problem-list-auto-update
          title: Update LeetCode problem data
          commit-message: Update LeetCode problem data
          body: ""
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          delete-branch: true
